.eslintrc.yml, .github/workflows/tests.yaml, .gitignore, README.md, __tests__/tests.js, package-lock.json, package.json
Automated tests will help to reduce the risk that we ever intentionally break the map (aka "Continous Integration" or CI). Those will run using GitHub Actions every time someone opens a PR or merges a PR. They can only merge their PR once the tests are working ("green").
People can also run these tests locally by using `npm test`. 
This also adds some other commands:
* `npm start`, which will use `http-server` to start the site. (While you could simply open up `index.html`, it won't properly load all the assets so the map will look empty.)
* `npm fmt` to run an autoformatter called Prettier, which formats our code like fixing indentation. 
* `npm lint` to run Prettier in check-only mode and to run a tool called ESLint that checks for common issues/bugs.
=> Add tests, CI, and README

__tests__/script.integration.test.js, __tests__/script.unit.test.js, js/script.js
To fix https://github.com/ParkingReformNetwork/parking-lot-map/issues/10,  I'll need to make a structural change to `setUpCitiesLayer`. 
Before doing that, I want to have better test coverage and clearer code. I split this up a precursor PR to keep code review simpler.
This changes how we calculate the share link if the URL already has a `#`. Currently, the only use of a `#` on our site is for setting a pre-selected city. So, replacing the `#` entirely with the new value makes the code much simpler.
=> Test and refactor the share link feature

__tests__/script.integration.test.js, js/script.js
Close https://github.com/ParkingReformNetwork/parking-lot-map/issues/10.
To simplify our support for loading from a share link, the `<option>` values for the city `<select>` are now the normalized city names, like `anchorage` and `fort worth`. This is not a future-proof scheme, per https://github.com/ParkingReformNetwork/parking-lot-map/issues/10, but it can be improved in a follow up.
We no longer use jQuery in this specific part of the codebase. jQuery is no longer necessary thanks to improvements in native JavaScript the past 15 years. Native JavaScript has much better performance.
=> Fix loading from a share link not working

index.html, js/script.js
This is much easier to read than the old `Promise.then()` interface. Yay modern JavaScript!
Async/await is simply "syntactic sugar". This should have no impact on the actual program.
=> Use async/await

package.json
Parcel was using the default of `/` for loading CSS/JS files, e.g. `href="/index.b09ca253.css"`. That tells the browser to look for `https://parking-reform.org/index.b09ca253.css"`.
Instead, we want to load the files relative to `index.html`.
=> Fix Parcel's relative links in deploys

README.md, scripts/tests/update-lots.test.js, scripts/update-lots.js
`npm run update-lots -- 'My City, AZ' --add` will add that city as a new entry. Otherwise, we continue to error if the city is not found.
=> Add `--add` flag to `npm run update-lots`

scripts/base.js, scripts/tests/base.test.js, scripts/update-city.js, scripts/update-lots.js
The `update-city-boundaries` script failed when uploading the Birmingham data because it used `StraightLine` rather than `Polygon` like past entries. That caused Leaflet to fail to process the GeoJSON.
It doesn't matter which we use, as long as we respect the original data source. We already validate that there is only one `Feature`, which does matter.
=> Detect the geometry type automatically when updating data

index.html
These aren't used and slow down our site:
* leaflet.awesome-markers is only relevant if we use `L.awesomeMarkers`. We don't use anything like that.
* `font-awesome` is to load some icons, but we don't use any of them.
* `esri-leaflet.js` is an integration with ESRI that we don't use.
=> Remove unused script and CSS loads

index.html
1.9.3 is arguably better, but it changes the font size for the control menu so https://github.com/ParkingReformNetwork/parking-lot-map/pull/46 is on hold until we decide the priority.
Meanwhile, we can get several years of improvements by going to 1.7.1, which renders the same as before.
=> Upgrade Leaflet to 1.7.1

.eslintrc.yml, .parcelrc, package-lock.json, package.json, src/tests/script.integration.test.js
We need this to be able to use ES6 modules (imports) with Jest.
We tell Parcel to ignore Babel.
=> Set up Babel

.github/workflows/deploy.yaml, package-lock.json, package.json, src/tests/setUpSite.test.js
This is prework for continuous deployment. 
We'll have the deploy workflow run on every push to `main`. Before a deploy, we want to confirm that the `dist/` folder works. That's a more relevant test than the source code working.
So, `serve-dist` will use `http-server` to start up the `dist/` folder. Then, `test-dist` will run the integration tests, but on port 8080 rather than 1234.
=> Add `serve-dist` and `test-dist` commands

.github/workflows/deploy.yaml, README.md, package.json
We'll now deploy the site when landing every pull request.
This will make it easier for us to frequently improve the site, especially loading new data.
Crucial to this is that we have ample testing. We should continue expanding the testing as we discover new issues.
=> Use continuous deployment

.eslintrc.yml, .gitignore, package.json, scripts/base.js, scripts/update-city.js, scripts/update-lots.js
This allows us to import from `src/js`.
Prework for https://github.com/ParkingReformNetwork/parking-lot-map/issues/62.
=> Switch to ES6 modules for `scripts/`

README.md, data/cities-polygons.geojson, data/parking-lots.geojson, scripts/base.js, scripts/tests/base.test.js, scripts/tests/data/original-data.geojson, scripts/update-city.js, scripts/update-lots.js, src/js/setUpSite.js, src/tests/cityId.test.js
Part of https://github.com/ParkingReformNetwork/parking-lot-map/issues/62.
In a follow up, we can sort the GeoJson files. Then, that will allow us to set up the city toggle before loading the map and avoid sorting inside the script.
=> Store city ID in GeoJSON files

src/js/setUpSite.js
Closes https://github.com/ParkingReformNetwork/parking-lot-map/issues/62. 
We now add the cities to the top toggle immediately, wheres before we had to finish creating the map and loading the cities boundaries.
This also makes the default of Columbus more obvious.
=> Add options to cities toggle right away

index.html, src/tests/setUpSite.test.js
This option was confusing once the site loads. It didn't actually work, and its semantics are unclear anyways.
It's somewhat useful when the site is first loading, but we set up the city toggle so fast (especially after https://github.com/ParkingReformNetwork/parking-lot-map/pull/71) that it doesn't matter. It's fine to show an empty select box for a couple of milliseconds.
=> Remove "Select a city" option from city toggle

.eslintrc.yml, package.json, src/js/setUpSite.js, src/js/vendor/leaflet.zoomhome.js
No manual changes were made, other than using `export default`. I ignored anything requiring manual changes.
This makes the code easier to understand and is prework to stop using the global `L`.
=> Modernize and ESLint zoomhome.js

src/js/setUpSite.js, src/js/vendor/leaflet.zoomhome.js
This makes the code easier to understand and goes in the direction of Leaflet 2.0, which says it will switch to using modern JavaScript like its classes.
Prework for not using the L global.
The zoom home button looks and works the same as before.
=> Define ZoomHome as a normal class

src/js/setUpSite.js, src/js/vendor/leaflet.zoomhome.js
This makes the code easier to understand and is more aligned with modern JavaScript.
The Leaflet devs have also announced that Leaflet 2.0 will stop having the `L` global, so this is prework.
Theoretically, using more precise imports allows Parcel to use "tree shaking" to only include the JavaScript we actually use. The bundle size is the same before and after this PR, so it doesn't look like it's happening. But maybe with Leaflet 2.0 they will redesign their code to allow that to happen.
=> Stop using `L` global

index.html, package-lock.json, package.json, src/css/style.css, src/js/fontAwesome.js, src/js/setUpSite.js, src/js/vendor/leaflet.zoomhome.js
Closes https://github.com/ParkingReformNetwork/parking-lot-map/issues/51.
This uses Parcel's "tree shaking" to only bundle the icons we actually use.
This also results in Font Awesome now using SVGs, which are better and scale perfectly regardless of screen size.
=> Only load the Font Awesome icons we actually use

src/js/fontAwesome.js, src/js/vendor/leaflet.zoomhome.js
This is much more intuitive than a home icon, which wasn't clear what it was.
We went with the globe rather than a US flag because we want to expand to Canada and Mexico.
=> Switch home icon for globe icon

.parcelrc
See https://github.com/parcel-bundler/parcel/issues/8938. This has been breaking the staging deploy since https://github.com/ParkingReformNetwork/parking-lot-map/pull/78.
Turns out we didn't need this config. It was only to silence Parcel complaining about Babel. We probably don't need it now because we don't have a `.babelrc` file like when I first tried adding Babel.
=> Workaround scope hoisting bug in Parcel

.parcelrc, package-lock.json, package.json
First part of https://github.com/ParkingReformNetwork/parking-lot-map/issues/58.
We then need to make sure the server is configured to use the compressed files.
We build the original uncompressed, gzip compressed, and brotli compressed. The server will determine which version to send based on the client.
`npm run build` now results in this:
```
124k index.17342985.css
17k index.17342985.css.br
21k index.17342985.css.gz
342k index.17342985.css.map
32k index.17342985.css.map.br
49k index.17342985.css.map.gz
4.0k index.cb0a4f29.css
932 index.cb0a4f29.css.br
1.2k index.cb0a4f29.css.gz
12k index.cb0a4f29.css.map
1.8k index.cb0a4f29.css.map.br
2.1k index.cb0a4f29.css.map.gz
216 index.e87b1b9a.css
137 index.e87b1b9a.css.br
170 index.e87b1b9a.css.gz
633 index.e87b1b9a.css.map
274 …
```
=> Enable compression

package-lock.json, package.json, src/css/style.css, src/css/vendor/leaflet.zoomhome.css, src/js/setUpSite.js
Closes https://github.com/ParkingReformNetwork/parking-lot-map/issues/54. This brings more improvements to e.g. accessibility and touch screen support.
Leaflet changed some of its CSS, so I had to manually tweak our CSS for the font size of the left controls. And use XL instead of large for the share icon.
=> Update to Leaflet 1.9

index.html, src/css/style.css
I tried using this from our main site:
<link rel="preload" href="https://parkingreform.org/wp-content/astra-local-fonts/poppins/pxiByp8kv8JHgFVrLCz7Z1xlFQ.woff2" as="font" type="font/woff2" crossorigin="">
But it failed to load when developing because of CORS (cross origin resource policy), which doesn't let us use the font other than on parkingreform.org
=> Use the same font as main site

src/js/setUpSite.js
This results in Parcel using code splitting: https://parceljs.org/features/code-splitting/. The parking lots GeoJSON data has its own JavaScript file.
That allows us to have a faster initial page load, such as setting up the city toggle and city boundaries. We still load the city data eagerly because it's essential to the page rendering, unlike the parking lots.
=> Lazy load parking data

src/js/setUpSite.js
The approach didn't work. We need to use something like https://github.com/ParkingReformNetwork/parking-lot-map/pull/93.
=> Revert "`#no-lots` in URL hides parking lots (#92)"

index.html, src/js/setUpSite.js
This allows us to push this lots toggle functionality to production. Tony thinks it may be useful in the future.
=> Hide parking lots toggle unless #lots-toggle in URL

package.json, src/js/setUpSite.js, tests/app/setUpSite.test.js
This is a safer and more modern way to write to the clipboard.
We couldn't do it before because I couldn't get things to work with Puppeteer. Playwright Just Works.
=> Use modern `navigator.clipboard` API

package-lock.json, package.json
I forgot to do this when switching from Jest to Playwright. Fewer dependencies are good from a supply chain health and security perspective.
=> Uninstall puppeteer

data/score-cards.json, scripts/add-city.js, src/js/setUpSite.js, tests/app/setUpSite.test.js
This is important to explain how our methodology works.
This PR also regroups and edits the name of some of the score card entries so that it's more precise. That reduces information overload.
=> Add city type to score card

src/js/setUpSite.js
I don't think this was intentional -- it's currently the default behavior. It makes it confusing how to get the popup back.
=> Don't close popups when clicking map

index.html, src/css/_controls.scss, src/css/_header.scss, src/js/setUpSite.js, tests/app/setUpSite.test.js
Flexbox results in much more robust responsiveness, i.e. support for different screen sizes. Note in the pictures how the grey background didn't work properly before on mobile.
This PR also gets rid of bolding in the header because it makes the site look less professional.
=> Improve the header to be responsive

src/css/style.scss
You could see the issue by setting `z-index: 3000;` on `#map`, which would cover the header.
=> Fix map being hidden by header

src/js/setUpSite.js
Why this refactor?
This simplifies when scorecard updates. 
Before, there were many different cases in which a scorecard would update, like the dropdown changing, the user panning to a different city, or the user clicking on a city. 
Now, the scorecard only updates to the city closes to the center of the screen. So, when the dropdown changes, the map snaps to city, which will also automatically update the scorecard.
=> Refactor updating scorecard

index.html, package-lock.json, package.json, src/css/_header.scss, src/js/dropdown.js, src/js/setUpSite.js, tests/app/setUpSite.test.js
Solves https://github.com/ParkingReformNetwork/parking-lot-map/issues/134
=> James lowenthal/134/replace dropdown with choices js

src/css/_header.scss
See: https://github.com/ParkingReformNetwork/parking-lot-map/issues/177
IOs on mobile autozooms for fonts in input elements < 16px for accessibility reasons.
This issue does not show up in devtools, use https://ngrok.com/ to try this out on your mobile phone.
If you don't have an iphone please test with your android or other smartphone (if you have one) as this would be useful data as well.
=> Add more accessible font to prevent autozoom on iOs

data/score-cards.json, scripts/add-city.ts, src/js/setUpSite.ts, src/js/types.ts
I realized from the book refactoringui.com that it's noisy to show this when irrelevant.
That allows us to improve our data modeling. We now use `null` when the URL and parking score are not set.
Before:
After:
=> Don't show parking score if not relevant

index.html, src/css/_about.scss, src/css/_header.scss, src/js/dropdown.ts, src/js/setUpSite.ts, tests/app/setUpSite.test.ts
With the new choices.js dropdown, it's reasonably obvious what the city dropdown is for. 
The label takes up valuable screen real estate. It also adds noise to the information hierarchy, reducing attention to the other UI elements.
<details><summary>before: mobile</summary>
</details>
<details><summary>before: desktop</summary>
</details>
<details><summary>after: mobile</summary>
</details>
<details><summary>after: desktop</summary>
</details>
We still might want to redesign the header for mobile, but this is a good first step.
=> Remove redundant "select a city" label

src/css/_controls.scss, src/css/theme/_touchable-icons.scss
Our zoom controls were too small. Touch targets should ideally be 44px x 44px. We had 30px x 30px. I went with 40px for now as a compromise to save space - we could increase to 44 after everything is redesigned.
This also increases the font size of the layer toggle.
Finally, the PR adds code for icons, although it's not yet used. It sets the minimum icon size as 20px x 20px, whereas we had 16px x 16px before. Claude generated this Sass code.
<details><summary>before</summary>
</details>
<details><summary>after</summary>
</details>
=> Increase size of zoom controls

src/css/_controls.scss, src/css/theme/_touchable-icons.scss, src/css/vendor/bootstrap.css, src/js/setUpSite.ts
Follow up to https://github.com/ParkingReformNetwork/parking-lot-map/pull/199.
* Uses touch target 44 x 44px, not 40 x 40px. On my iPhone, 40 x 40px is still fairly small. Now, we follow the web accessibility standard.
* Increases the size of the layers touch targets to 44px height. To make the touch targets look distinct and not have weird space in the middle, I added a 1px border, which mirrors the zoom-in and out buttons.
* Uses our colors for all the borders. I still don't love the color, but it can be changed later. This at least switches to our own color
* Consistently use `font-size-md` and non-bold text
* Vertically aligns radio buttons with label text
* Renames "Light" layer to "High contrast" for better clarity
Ideas for additional improvement:
* prettier radio button
* choose a …
=> Further improve design of left controls

index.html, src/css/_controls.scss, src/css/_header.scss, src/css/theme/_touchable-icons.scss, src/js/about.ts, tests/app/about.test.ts
One issue with our styling is that it's pretty haphazard. It's never clear why certain values are chosen, and we often repeat values too.
By using `calc()`, we can make the code more self-documenting and flexible. When you change a variable, it should correctly update all the other styling code automatically.
--
This also recalibrates the icon sizes & removes the icon mixin, which didn't end up working well with the project.
--
This PR should have no impact on the end user. It is only a refactor.
=> Use `calc()` in Sass

src/js/about.ts, src/js/setUpSite.ts, src/js/share.ts
This reduces the nesting of everything, which makes the code more readable. We also now use `instanceof` for runtime checks, whereas before we were using type casts which could have been wrong.
=> Use early returns

src/css/_scorecard.scss, src/js/about.ts, src/js/setUpSite.ts, src/js/share.ts, tests/app/setUpSite.test.ts
This PR:
* removes a bunch of unnecessary CSS rules
* renames some classes to be more clear
* replaces the HTML structure of `.details-title: .details-key` to instead be a `<p>`, since we want to move away from the `key: value` format in the scorecard
The end user interface is roughly the same as before; this is mostly a refactor.
=> Refactor scorecard in preparation for accordion

src/css/_scorecard.scss, src/js/setUpSite.ts
Even though I'll be proposing moving the share link icon to the top header, it will still be in the scorecard as part of the initial accordion revamp. So it's important that the styling is right.
This uses flexbox so that the share link icon is always positioned in the correct spot, whereas using `float` was haphazard.
It also allows us to shrink the width of the scorecard.
=> Use flexbox for scorecard header

index.html, src/css/_controls.scss, src/css/_donate.scss, src/css/_header.scss, src/css/_scorecard.scss, src/js/scorecard.ts, src/js/setUpSite.ts, src/js/share.ts, tests/app/setUpSite.test.ts
This improves the header:
* Makes all touch targets at least 44px, the accessibility minimum
* Moves copy link icon to the header
* Removes the "Parking Lot Map" text
* adds a teal border underneath
It also adds more explanatory text to the header in the scorecard, now saying "Parking lots in City, ST" to better explain what people are seeing.
<details><summary>before: mobile</summary>
</details>
<details><summary>before: desktop</summary>
</details>
<details><summary>after: mobile</summary>
</details>
<details><summary>after: desktop</summary>
</details>
--
Removing the "Parking Lot Map" text achieves two things:
* Allows us to fit the header on a single line, even on mobile. This allows more screen real estate for the map itself and scorecard
* Improves information hierarchy. The name …
=> Revamp header layout

data/score-cards.json, src/css/_scorecard.scss, src/js/scorecard.ts, tests/app/setUpSite.test.ts
<details><summary>before</summary>
</details>
<details><summary>after</summary>
</details>
Goals of the revamp:
* Give more context, especially for the parking score
* Make it more clear where one entry starts and the other ends
* De-emphasize the view links button, which was the most visually striking element in the scorecard even though it's not the most important in the information hierarchy
=> Revamp scorecard "additional details"

src/css/_scorecard.scss, src/js/fontAwesome.ts, src/js/scorecard.ts, tests/app/setUpSite.test.ts
On iOS, the up-right arrow was rendering as an emoji and it looked weird. By using font awesome, the styling will be consistent.
=> Use font-awesome icon for external link

src/css/_about.scss, src/css/_controls.scss, src/css/_header.scss, src/css/_scorecard.scss, src/css/theme/_colors.scss
Changes:
* Uses the exact color from the logo for the top header
* Removes unused `$black-translucent` and consolidates the two gray colors
* Renames `$gray-light-translucent` to `$gray-translucent`
I'm still not very happy with `$gray-translucent`, but I don't know how to fix it. It's used for outer borders of UI elements, so I don't feel I can fix it until figuring out the depth idea from Refactoring UI.
Before:
After:
=> Better align colors to logo

src/css/_header.scss, src/css/_scorecard.scss, src/css/theme/_breakpoints.scss
The map looked great when going directly to the full screen site. But it's too big when embedded in `/resources/parking-lot-map` as an iframe.
This PR fixes that by:
* making scorecard narrower on small screens
* hiding the "view fullscreen" icon on mobile. It's not even very useful to do this on mobile because the fullscreen app is only a few pixels bigger than the iframe
<details><summary>before</summary>
</details>
<details><summary>after</summary>
</details>
=> Fix spacing on mobile iframe

src/css/_header.scss, src/css/_logo.scss, src/css/_scorecard.scss, src/css/theme/_breakpoints.scss
Due to the iframe, it's common for us on desktop to have a small render of the map, but still much wider than mobile. https://github.com/ParkingReformNetwork/parking-lot-map/pull/216 was overly aggressive in hiding the fullscreen icon in that case; there, the full-screen icon is actually quite useful.
This defines a new smaller breakpoint and adjusts some responsive styling to be bigger on small, but not xsmall, screens.
=> Define `xxs` breakpoint

src/css/_attribution.scss, src/css/_logo.scss, src/css/style.scss
* Makes the font bigger on > small screens
* Uses a non-transparent background, which is more clear on our high-contrast map layer.
Before:
After:
=> Improve styling of attribution

src/css/_header.scss, src/js/iframe.ts, src/js/setUpSite.ts
The button does nothing when you're already at https://parkingreform.org/parking-lot-map. It's only useful when you're inside an iframe.
=> Hide full-screen icon when not an iframe

src/css/_logo.scss
It was covering the map too much on mobile.
=> Reduce size of logo

src/css/_controls.scss, src/css/_logo.scss, src/css/_scorecard.scss, src/js/scorecard.ts, tests/app/communityMaps.test.ts
It's important that the disclaimer always shows, such as screenshots. It's unfortunate that this disclaimer takes up valuable vertical space on mobile, but I couldn't think of any ways to minimize the impact:
* Can't use 12px font-size without violating accessibility. Already at 14px.
* We could reduce the padding in the scorecarad, but it's already quite tight
* I couldn't think of shorter copy because it's important that we have the email address 
This PR does reduce margins for the map controls to regain some space.
=> Add back community contribution disclaimer

src/css/_controls.scss, src/css/_header.scss, src/css/_logo.scss, src/css/_scorecard.scss, src/css/theme/_icons.scss, src/css/theme/_spacing.scss
The only user-facing change is the controls having 10px rather than 8px of gap between. This is a refactor to make our code more consistent and DRY.
=> Refactor spacing CSS code

src/js/scorecard.ts
Tung pointed out it was confusing to link the "Community-maintained" text in the disclaimer because people thought it would link to more info about that program, not the email of the maintainer.
Instead, Tung had the idea of putting the email address in the Additional details.
This alternative is great because it keeps the disclaimer at one line, which we need to not cover the map on mobile.
=> Tweak contributor disclaimer

index.html, src/css/_about.scss, src/js/about.ts, src/js/setUpSite.ts, tests/app/about.test.ts
* Renames variables/classes to be more clear
* Uses `hidden` rather than `display: none`. Claude told me yesterday that `hidden` is better. The code is more clear also.
=> Refactor about popup code

src/css/_about.scss, src/css/_controls.scss, src/css/_header.scss, src/css/_scorecard.scss, src/css/theme/_borders.scss, src/css/theme/_colors.scss
Uses a consistent style of 1px borders with `hsla(0, 0%, 0%, 0.4)`, and removes box shadows. 
I played around with box shadows, but it was too hard to get something that consistently looked good. A flat design is simpler.
Before:
After:
=> Align borders

src/css/_attribution.scss
This makes the style consistent so that there is better contrast against the white map. 
On mobile, we don't have a left border:
=> Add border around attribution

src/css/_map.scss, src/css/style.scss, src/css/theme/_resets.scss, src/css/theme/_typography.scss, src/css/vendor/bootstrap.css
Sibling PR to https://github.com/ParkingReformNetwork/reform-map/pull/397. The end style is the same as before, but this keeps chipping away at the Bootstrap code which Mandates Map doesn't have.
Also removes styling for `hr`, which we no longer use.
=> Set up resets file

src/css/_dropdown.scss, src/css/_header.scss, src/css/style.scss, src/js/dropdown.ts
On large screens, choices.js has a little "select" label to the right of every entry. But there is no good reason for that. The UI is obvious already.
Fixing this allows us to keep the search/select a consistent 220px regardless of mobile vs desktop, meaning we cover less of the map.
Before:
After:
=> Hide "select" text in search component

src/css/_about.scss, src/css/_controls.scss, src/css/_dropdown.scss, src/css/_logo.scss, src/css/_scorecard.scss, src/css/theme/_zindex.scss
* Fixes the z-index. The scorecard was being hidden by the logo
* Fixes horizontal scroll showing up in the about popup due to the iframe code
* Makes the logo smaller on bigger screens
=> Fix mobile styling issues

index.html, src/css/theme/_resets.scss, src/css/vendor/bootstrap.css, src/js/about.ts
Improves a few things:
* Uses `button` rather than `div`
* Associates the about icon with the popup
* Uses `.sr-only` to better describe some of the icons
* Hides the icons from screen readers
* Moves the title to the outer div rather than the inner icon, which is useful for sighted users.
=> Improve icon accessibility

index.html, src/css/_about.scss, src/css/_scorecard.scss, src/css/theme/_resets.scss, src/js/scorecard.ts, src/js/setUpSite.ts, tests/app/setUpSite.test.ts
Benefits of this change:
* The scorecard doesn't disappear temporarily when moving around the map
* Simpler code, such as not having to override Leaflet styling. This will also help with the mandates map
This also DRYs some other code for `<ul>` and line-height.
=> Don't use Leaflet popup for scorecard

src/css/_scorecard.scss
This was leftover from when the link icon used to be in the scorecard.
=> Remove unnecessary scorecard title rules

README.md
Separates out the node definitions from the relationships. The end result is the same.
=> Make Mermaid diagram more readable

README.md
I forgot two important features:
* The fullscreen icon uses the URL of the current city
* When scrolling around the map, we load all cities in view. If it's the most-central city, we load it
* When zoomed in enough, clicking inside a city boundary chooses that city and snaps the map to it
=> Add state diagram for fullscreen icon & map changing what's loaded

src/js/Observable.ts, src/js/about.ts, src/js/scorecard.ts
This PR splits out state management from how to display the UI/DOM. Now, for the scorecard accordion and about popup, we have two distinct functions:
- how to display the UI element given a boolean state
- how to update the boolean state via event listeners, and what the initial value is
Those two functions no longer have tight coupling, which makes them much easier to understand.
Specifically, we use the "Observable" design pattern (aka pub-sub). I also considered switching to Svelte, which has reactivity built-in, but I wanted to start with this simpler approach.
A follow up will use this pattern for the rest of the app.
=> Use reactive pattern for about and scorecard

src/js/Observable.ts, src/js/about.ts, src/js/scorecard.ts
Before, you had to explicitly call every subscriber with the initial state. Now, you can call `myObservable.initialize()` to do that.
Beyond DRY, this is helpful to encapsulate who the subscribers are. For example, for the selectedCity observable, we'll have subscribers from several files and we don't want to have to couple them all together.
=> Add `Observable.initialize()`

src/js/ParkingLotLoader.ts, src/js/setUpSite.ts, src/js/types.ts
Before, it was possible to load parking lot data multiple times due to race conditions. If we had >1 event triggering a map load, then we'd have two requests concurrently.
We need a thread-safe way to only load the data once, i.e. something that keeps track of in-flight requests. We can do that with a `Map<CityId, Promise>`, which makes sure we never have more than one `Promise` for a given city. Once the Promise is complete, we then add the city to `ParkingLotLoader.loadedCities`.
=> Fix lot data double loading

src/js/CitySelectionState.ts, src/js/GlobalState.ts, src/js/about.ts, src/js/dropdown.ts, src/js/scorecard.ts, src/js/setUpSite.ts, src/js/share.ts
As explained in https://github.com/ParkingReformNetwork/parking-lot-map/pull/254, this separates out state management from how to render the UI. 
This PR adds `CitySelectionState`:
```typescript
type CitySelectionState = {
cityId: CityId;
shouldSnapMap: boolean;
};
```
- 5 of our UI elements depend on `CitySelectionState`
- There are 3 ways to update `CitySelectionState`: the dropdown, moving the map position, and clicking a city boundary
=> Use reactive pattern for city selection state

src/js/dropdown.ts
Closes https://github.com/ParkingReformNetwork/parking-lot-map/issues/185. Otherwise, when the viewport is too short, the search would open above the select element.
=> Dropdown always opens below header

index.html
The app is usually accessed via an iframe. If you click links currently, the new page is in the iframe itself. This is really confusing. We could use `target=_top` to replace the current page, but Tony has said in the past that we should go to a new tab.
We now consistently use the up-right arrow icon with every external link to make more explicit that the links go to a new tab.
=> Open all links in a new tab

package.json, packages/primary/package.json, packages/shared/package.json
Proper proper fix of https://github.com/ParkingReformNetwork/parking-lot-map/pull/299. I had put the target on packages/shared, not packages/primary 🤦 This config fixes the HTML and logo to not have a prefix, rather than `/`.
=> Fix target being declared in wrong place

.github/workflows/deploy-prod.yaml, .github/workflows/deploy-staging.yaml
Deploys to `/ct-parking-lots-staging` and `/ct-parking-lots`.
We use a single workflow still for prod to keep things simple. I considered having a distinct workflow for deploying to prod for each. However, given that the apps are functionally identical, it did not seem worth it.
=> Deploy CT map

package.json, packages/ct/data/city-boundaries.geojson, packages/ct/data/city-stats.json, packages/ct/data/parking-lots/hartford.geojson, packages/ct/data/parking-lots/new-haven.geojson, packages/ct/src/js/main.ts, packages/primary/data/city-boundaries.geojson, packages/primary/data/city-stats.json, packages/primary/data/parking-lots/st-louis-mo.geojson, packages/primary/data/parking-lots/st-petersburg-fl.geojson, packages/shared/package.json, packages/shared/src/js/cityId.ts, packages/shared/src/js/types.ts, packages/shared/tests/cityId.test.ts, pnpm-lock.yaml
The CT map will have entries like `Hartford - rail station`, which should convert to `hartford-rail-station`. We can do that with Lodash's kebabCase.
That results in changing `st.` to become `st`, which is a good change anyways. We ensure we still pre-load the correct place if someone uses an anchor with the old style of `st.`.
=> Support new Connecticut city IDs

packages/shared/src/js/city-ui/dropdown.ts, packages/shared/src/js/city-ui/dropdownUtils.ts, packages/shared/src/js/model/types.ts, packages/shared/tests/dropdownUtils.test.ts
Generalizes https://github.com/ParkingReformNetwork/parking-lot-map/pull/239 to the new CT map where the city names won't have states and will have descriptors like `- rail station`.
We need a new file for the dropdown pure functions to be able to test the code because `choices.js`'s import uses `window`, which isn't available in Playwright's node environment.
=> Dropdown search can handle CT city names

packages/ct/data/city-stats.json, packages/primary/data/city-stats.json, packages/primary/tests/dropdownGroups.test.ts, packages/scripts/src/add-city.ts, packages/shared/src/js/city-ui/scorecard.ts, packages/shared/src/js/model/types.ts
This is more maintainable. The data set is so small that I'm not worried about the marginal size in storage.
=> Use explicit null values in city-stats.json

.eslintrc.yml, packages/scripts/package.json, packages/scripts/src/add-city.ts, packages/scripts/src/base.ts, packages/scripts/src/update-city-boundaries.ts, packages/scripts/src/update-lots.ts, packages/scripts/tests/base.test.ts, pnpm-lock.yaml
- Using `ts-results` didn't make much sense because we weren't doing anything interesting with the results, such as deferring erroring. We wanted to error immediately. It added indirection
- I'm not sure why I was using anonymous functions rather than `function`
- I like putting `export` directly on the function rather than the bottom of the file
=> Use more conventional TS style in packages/scripts

packages/ct/src/css/overrides.scss, packages/ct/src/index.html, packages/shared/src/css/_controls.scss, packages/shared/src/css/_dropdown.scss, packages/shared/src/css/_scorecard.scss
Changes:
* Make scorecard title smaller on mobile on both maps so it doesn't cover as much of the map
* Truncate overly wrong dropdown entries when currently chosen
* Make the dropdown wider in CT map
* But we also don't make it the full width necessary of 300px because it makes the dropdown look way too wide for most entries.
=> Handle long entries on Connecticut map

.github/workflows/deploy-staging.yaml, .github/workflows/tests.yaml, packages/ct/src/index.html
- The image added for previews is the Stratford, CT map. [https://parkingreform.org/wp-content/uploads/2025/02/StratfordCT.png](https://parkingreform.org/wp-content/uploads/2025/02/StratfordCT.png)
- Updated/added the text descriptions.
- The original PRN map has `og:url` going to the [general Parking Lot Map resource page](https://parkingreform.org/resources/parking-lot-map/). Since there isn't an equivalent for the CT parking lot map I'm linking to [https://parkingreform.org/ct-parking-lots](https://parkingreform.org/ct-parking-lots) but could see an argument for [https://ctparkingreform.org](https://ctparkingreform.org). Happy to update either way.
- "Connecticut Parking Lot Map" is quite long, let me know if you think we should update it to "CT Parking Lot Map"
Preview of current FB …
=> Adding Open Graph/Twitter metadata for prettier preview cards
