index.html, js/script.js
Deleting commented out code improves readability and reduces confusion. Commented out code makes it more difficult to understand the actual working code. It can confuse readers about its relevance or whether it should be reactivated in the future.
Git reduces the risks associated with deleting commented-out code. It allows us to restore this code whenever we want.
=> Remove commented out code

.eslintrc.yml, .github/workflows/tests.yaml, __tests__/tests.js, package.json
This adds two tests:
1. The city toggle has all the cities we expect, based on the geoJSON.
2. We correctly load the score card for the city Anchorage. This also tests that changing the city correctly works.
Both tests dynamically determine the expected data by looking at the geoJSON. That means that when we update the data, the tests won't require any updates.
=> Test the city toggle and the score card

__tests__/script.integration.test.js, js/script.js
The only major missing test we have now is the parking lot map layer.
This is prework for https://github.com/ParkingReformNetwork/parking-lot-map/pull/16.
=> Add test for about popup & improve clipboard test

__tests__/script.integration.test.js, __tests__/script.unit.test.js, js/script.js
Closes https://github.com/ParkingReformNetwork/parking-lot-map/issues/14. 
This means that existing share link URLs will not go to the original city. We'll default back to Columbus in this case, which we agreed was fine.
=> Future proof URL scheme for share link button

.gitignore, .parcelrc, README.md, __tests__/script.integration.test.js, package-lock.json, package.json
Parcel is a "bundler" that automatically optimizes HTML, CSS, JavaScript, and other assets, like minimizing them.
Benefits:
- Improved performance: Bundling and minifying code reduces file size and load times.
- Browser compatibility: Transpiles (rewrites) modern JavaScript into JS understood by older browsers.
When we deploy, we will now run `npm run build` and then simply copy the `dist/` folder. For example, this is what it puts into `dist/`:
```
dist/index.html                                         7.54 KB    789ms
dist/parking-reform-network.deea73d9.png                 7.4 KB    241ms
dist/index.f18561bf.css                               109.55 KB    238ms
dist/glyphicons-halflings-regular.cca02454.eot         19.66 KB    761ms
dist/glyphicons-halflings-regular.a3cea8f3.woff2 …
```
=> Switch to Parcel (for now)

.eslintrc.yml, index.html, js/script.js
jQuery is no longer necessary thanks to improvements in native JavaScript the past 15 years. Native JavaScript has much better performance.
=> Stop using jQuery

.eslintrc.yml, __tests__/script.integration.test.js, js/script.js
Splits up `generatePopupContent` into two functions:
* `setUpShareUrlClickListener`, which modifies the DOM
* `generateScorecard`, which simply generates the string for the HTML for the popup
We already have a good integration test for this code.
=> Refactor score card code

scripts/tests/data/parking-lots/empty-update.geojson, scripts/tests/data/parking-lots/original-data.geojson, scripts/tests/data/parking-lots/too-many-updates.geojson, scripts/tests/data/parking-lots/valid-update.geojson, scripts/tests/update-lots.test.js, scripts/update-lots.js
I want to keep changing this script, like allowing you to add new cities. So, I want testing to make sure I don't break things.
=> Test and refactor update-lots.js

README.md, package.json, scripts/base.js, scripts/tests/base.test.js, scripts/update-city.js, scripts/update-lots.js
Closes https://github.com/ParkingReformNetwork/parking-lot-map/issues/24.
=> Add `npm run update-city-boundaries`

src/js/script.js
I don't know why, but this doesn't seem necessary anymore. Yay!
=> Stop setting `pane` global variable

.github/workflows/deploy.yaml
We will trigger deploys to production via a Git tag.
=> Deploy to staging

src/js/setUpSite.js
Reverts https://github.com/ParkingReformNetwork/parking-lot-map/pull/23. Now that we have ES6 modules, it's less of a problem to have globals like before. We don't have any magic values like `L` that aren't explicitly defined.
And all the pure functions were moved to `cityId.js`. Every single function in `setUpSite` has a side effect, so the benefit was much lower than before.
=> Go back to using globals in setUpSite thanks to ES Modules

src/js/setUpSite.js
No need to use a lazy function anymore to define the constant. It's fine to use `L` at the global level now that we have ES6 modules.
=> Simplify module level constants

index.html, src/js/setUpSite.js
Sometimes the first page-load on mobile does not properly load the map and only shows the top 20%. 
I'm not sure why that is, but ChatGPT says we're not properly awaiting the completion of the promise. So hopefully this helps.
=> Use `async await` again to see if it fixes mobile loading

index.html, src/js/setUpSite.js
Another attempt to fix https://github.com/ParkingReformNetwork/parking-lot-map/pull/89, which didn't do the trick.
=> Try to fix initial page load issue

index.html, src/js/setUpSite.js
Better approach than https://github.com/ParkingReformNetwork/parking-lot-map/pull/92.
=> Another way to toggle lots data

data/city-boundaries.geojson, data/parking-lots.geojson, data/score-cards.json
Closes https://github.com/ParkingReformNetwork/parking-lot-map/issues/99
=> Fix missing state for San Antonio

.github/workflows/deploy-prod.yaml, .github/workflows/deploy-staging.yaml
Better to centralize these secrets now that the Mandates Map is using CD too.
=> Switch to organization level GH Actions secrets

src/js/setUpSite.js, tests/app/setUpSite.test.js
Thomas thinks this is a better default because it's a popular city and surprising how much is parking.
=> Change default city to Atlanta

src/css/_about.scss, src/css/_controls.scss, src/css/_copied-link.scss, src/css/_donate.scss, src/css/_header.scss, src/css/_scorecard.scss, src/css/style.scss
None of the code was changed. It's only rearranged now into dedicated files.
Sass and Parcel combine all these files into one single minimized output. So this has zero negative impact on users.
=> Split up CSS into Sass modules

src/js/setUpSite.js
The Stamen layer stops working well when zoomed in too much.
=> Reduce max zoom to 18

src/js/about.js, src/js/setUpSite.js, tests/app/about.test.js, tests/app/setUpSite.test.js
Better UX, particularly for mobile users.
=> Clicking outside of About popup will close it

src/css/style.scss
See https://github.com/ParkingReformNetwork/reform-map/pull/213.
=> Fix height on mobile

index.html, src/js/setUpSite.js
The Stamen Design team reached out asking that we make this migration.
=> Migrate to Stadia Maps

data/score-cards.json
Accidentally used metro population instead of urbanized population.
=> Fix urbanized population of the newly added 16 cities

.github/workflows/deploy-prod.yaml
Has been causing errors in workflow
=> Add no times to deploy-prod workflow

src/js/setUpSite.js
Problem: 
This PR fixes this and the result looks like this:
=> Fix console error when no city is visible

data/score-cards.json
Missed parking score and percentage.
=> Update Las Vegas

src/js/setUpSite.ts
I'm going to make some changes to the scorecard based on the book refactoringui.com. This is a refactor to prep for the changes.
=> Refactor score card HTML generation

.github/workflows/deploy-prod.yaml, .github/workflows/deploy-staging.yaml
=> Fix deploys

src/css/_about.scss, src/css/_colors.scss, src/css/_header.scss, src/css/_scorecard.scss
This implements two recommendations from the book https://www.refactoringui.com:
1. Centralize your color scheme in one place
2. Use `hsl` rather than `rgb` or hex codes. It makes it much easier to see how colors relate to each other
It does not change any of the colors - this is only a refactor.
=> Switch to HSL

src/css/vendor/bootstrap.css
We don't use these HTML elements and are unlikely to. This PR gets us closer to being able to replace Bootstrap with our own styling.
=> Remove unused bootstrap code

src/css/vendor/bootstrap.css
The goal is to remove all of this code. In the meantime, this PR removes rules for elements we don't even use.
=> Remove more bootstrap rules

src/js/scorecard.ts, src/js/setUpSite.ts
No changes made to the actual code.
=> Move scorecard code to dedicated file

src/js/scorecard.ts, src/js/share.ts
They didn't accurately reflect how this code works.
=> Fix variable names in setUpShareUrlClickListener

index.html, package.json, src/css/_about.scss, src/css/vendor/bootstrap.css, src/js/scorecard.ts
This better uses semantic web and ARIA properties to make the site more accessible.
=> Improve accessibility

index.html, src/css/_scorecard.scss, src/css/style.scss, src/css/theme/_links.scss, src/js/scorecard.ts
=> Generalize code for external links

index.html, src/css/_about.scss, src/css/_header.scss, src/css/_logo.scss
=> Revamp about popup

index.html
The about popup now explains how to embed:
=> Add embed instructions

index.html, src/css/_header.scss
The Mandates Map is making this change because it will have several new icons. So keep it in sync.
=> DRY header icons

src/js/dropdown.ts, src/js/types.ts
Before:
After:
You of course can still search by city:
=> Improve search by state

index.html, src/css/theme/_links.scss, src/css/theme/_resets.scss, src/css/vendor/bootstrap.css
Keeps the map aligned with https://github.com/ParkingReformNetwork/reform-map/pull/410.
=> Move some bootstrap rules into theme

README.md, src/css/_controls.scss, src/js/setUpSite.ts
Also fixes bad style for the zoom controls I didn't realize we had.
=> Add missing state diagram interactions

src/js/cityId.ts, src/js/dropdown.ts, src/js/setUpSite.ts, tests/app/cityId.test.ts
This is more explicit modeling.
=> Use null rather than empty string

src/js/about.ts, src/js/cityId.ts, src/js/dropdown.ts, src/js/fontAwesome.ts, src/js/iframe.ts, src/js/scorecard.ts, src/js/setUpSite.ts, src/js/share.ts
I don't have a very good reason why we weren't using `function` to begin with. `function` is more intuitive and beginner-friendly.
=> Use function rather than anonymous funtions

src/js/ParkingLotLoader.ts, src/js/map.ts, src/js/setUpSite.ts
The layer only needs to be used by ParkingLotLoader, so it's best to encapsulate it in the class.
=> Move parking lot layer code into ParkingLotLoader.ts

src/css/_dropdown.scss
This fixes the styling if any entry is too long to fit on one line.
=> Use min-height for search entries

src/css/_controls.scss, src/css/_scorecard.scss, src/css/theme/_colors.scss
We already had this for the zoom controls. Now the map layer and the scorecard accordion have it.
=> Add hover color for buttons

package-lock.json, package.json, scripts/add-city.ts, scripts/base.ts, src/css/_dropdown.scss
They fixed a CSS bug we had a workaround for.
=> Upgrade to Choices.js 11

package-lock.json, package.json, scripts/add-city.ts, scripts/base.ts, src/css/_dropdown.scss
This reverts commit b2fb03d8014d0c188c4122cb1c649d676c4c8a47.
The deploy to staging failed because I think the CSS loading is broken.
=> Revert "Upgrade to Choices.js 11 (#273)"

index.html, package-lock.json, package.json, scripts/add-city.ts, scripts/base.ts, src/css/style.scss, src/js/dropdown.ts, src/js/fontAwesome.ts, src/js/map.ts
See https://github.com/ParkingReformNetwork/reform-map/pull/655.
=> Upgrade parcel

src/css/_about.scss, src/css/_logo.scss, src/css/_scorecard.scss
Breakpoints should appear after the root rules.
=> Adjust breakpoint code to avoid Sass deprecation

package-lock.json, package.json
See if it fixes a segfault we were getting when deploying to staging.
=> Downgrade to Parcel 2.12

src/js/CitySelectionState.ts, src/js/ParkingLotLoader.ts, src/js/citiesLayer.ts, src/js/data.ts, src/js/declarations.td.ts, src/js/dropdown.ts, src/js/main.ts, src/js/types.ts
Now all data loading happens in `data.ts` and gets passed as arguments to the other functions/classes. That will make it easier for us to load a new data set with Connecticut.
=> Parametrize data loading

packages/primary/src/js/data.ts, packages/primary/src/js/declarations.td.ts
The declarations file wasn't working well when adding `packages/ct`.
=> Simplify approach to JSON type declarations

packages/ct/src/js/main.ts, packages/ct/src/js/scorecard.ts, packages/primary/src/js/main.ts, packages/primary/src/js/scorecard.ts, packages/primary/tests/main.test.ts, packages/scripts/src/add-city.ts, packages/shared/src/js/bootstrap.ts, packages/shared/src/js/city-ui/scorecard.ts, packages/shared/src/js/model/types.ts
=> Make scorecard generic

packages/ct/data/city-stats.json
These were issues in the input CSV.
=> Fix parking percentages in CT map
